package at.reder.virussim.view;

import at.reder.virussim.listener.PlaygroundChangedListener;
import at.reder.virussim.model.Playground;
import javax.swing.JFrame;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author alex
 */
public class VirusSimFrame extends JFrame implements PlaygroundChangedListener {

    private static final Logger LOGGER = LoggerFactory.getLogger(VirusSimFrame.class);
    private final Playground playground;
    private int timestamp;
    private PlaygroundComponent playgroundComponent;

    /**
     * Creates new form VirusSimFrame
     *
     * @param playground
     */
    public VirusSimFrame(Playground playground) {
        this.playground = playground;
        this.timestamp = 0;
        initComponents();
        customInitComponents();
    }

    @Override
    public void playgroundChanged(Playground playground) {
        this.playgroundPanel.repaint();
    }

    private void customInitComponents() {
        this.playgroundComponent = new PlaygroundComponent(this.playground);
        this.playgroundPanel.add(this.playgroundComponent);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configPanel = new javax.swing.JPanel();
        nextTimestampButton = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        propertiesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playgroundPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("at/reder/virussim/view/Bundle"); // NOI18N
        nextTimestampButton.setText(bundle.getString("VirusSimFrame.nextTimestampButton.text")); // NOI18N
        nextTimestampButton.setFocusable(false);
        nextTimestampButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextTimestampButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nextTimestampButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTimestampButtonActionPerformed(evt);
            }
        });
        configPanel.add(nextTimestampButton);

        getContentPane().add(configPanel, java.awt.BorderLayout.LINE_START);
        getContentPane().add(infoPanel, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(propertiesPanel, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setViewportView(playgroundPanel);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextTimestampButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTimestampButtonActionPerformed
        this.playground.timeChanged(this.timestamp++);
    }//GEN-LAST:event_nextTimestampButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel configPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextTimestampButton;
    private javax.swing.JPanel playgroundPanel;
    private javax.swing.JPanel propertiesPanel;
    // End of variables declaration//GEN-END:variables
}
